services:
  ai_blog_app:
    container_name: ai_blog_app
    build:
      context: .
      dockerfile: ./django/Dockerfile
    image: ai_blog__app
    restart: always
    depends_on:
      - postgres_db
      - ollama_app
    env_file:
      - .env
    environment:
      WAIT_HOSTS: postgres_db:5432, ollama_app:11434
    command: bash -c "python manage.py runserver"
    ports:
      - ${DJANGO_PORT:-8000}:8000

  ollama_app:
    container_name: ollama_app
    build: ./ollama
    image: ollama
    restart: unless-stopped
    volumes:
      - ollama_volume:/root/.ollama
    env_file:
      - .env
    ports:
      - ${OLLAMA_PORT}:11434

  postgres_db:
    container_name: postgres_db
    build: ./postgres
    image: postgres_db
    restart: unless-stopped
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    # ports:
    #   - ${POSTGRES_PORT}:5432

volumes:
  postgres_db_volume:
  ollama_volume:
