version: "3.8"

services:
  ollama_app:
    container_name: ollama_app
    build: ./ollama
    image: ollama
    restart: unless-stopped
    volumes:
      - ollama_volume:/root/.ollama
    env_file:
      - .env
    ports:
      - ${OLLAMA_PORT}:11434
  
  postgres_db:
    container_name: postgres_db
    build: ./postgres
    image: postgres_db
    restart: unless-stopped
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    

volumes:
  postgres_db_volume:
  ollama_volume:
